### ISSUE TITLE
Matematicas discretas Practica 9

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-alan-ivan#1]
[Matematicas discretas Practica 9.pdf](https://github.com/user-attachments/files/17525543/Matematicas.discretas.Practica.9.pdf)

**Comment by Fidel20-01** [comment]
Evaluciaon de Practica 9
-Portada: 17/25
-Procedimiento:20/25
-Fotografias , ilustraciones y figuras:25/25
-Resultado y conclusiones:25/25
Total de puntos:87/100
Calificacion: 17/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
